propel:
  sf_guard_user_profile:
    _attributes: { phpName: sfGuardUserProfile }
    id:
    user_id:     { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    first_name:  varchar(20)
    last_name:   varchar(20)
    birthday:    date
    email:       varchar(255)

  products:
    _attributes: { phpName: Product }
    id:
    label:   varchar(255)

  product_i18n:
    _attributes: { phpName: ProductI18n }
    name:           varchar(255)
    description:    longvarchar

  product_category:
    _attributes: { phpName: ProductCategory }
    id:
    label:        varchar(255)
    tree_left:    integer
    tree_right:   integer
    tree_parent:  integer
    topic_id:     integer

  product_category_i18n:
    _attributes: { phpName: ProductCategoryI18n }
    name:           varchar(255)
    description:    longvarchar

